/**
 * Blog post body blocks — authored per post for Sprint C.
 * Blocks are simple types rendered by ArticleBody.
 */
import type { Block } from "./blocks";

type BlockMap = Record<string, Block[]>;

export const POST_BODIES: BlockMap = {
  "interior-cost-per-sqft-lahore-2025": [
    { type: "p", text: "Every month we get 40-60 inbound enquiries. About 80% start with the same question: 'how much per square foot?' This article is the answer we would give you on a site visit, in writing, with the assumptions spelled out so you can tell if the number applies to your project." },
    { type: "p", text: "These are real numbers from quotes we sent in the first half of 2025 for projects in Lahore. They include civil works, MEP (electrical, plumbing, basic HVAC distribution), joinery, and finishes. They exclude land, furniture beyond fixed joinery, soft furnishings, professional fees (architect/designer if separate), and any imported items landed at port." },
    { type: "h2", text: "The ranges, at a glance" },
    { type: "table",
      headers: ["Space type", "PKR / sqft", "Typical size", "Weeks on site"],
      rows: [
        ["Residential (mid-tier)", "3,500–5,000", "1-kanal (5,500 sqft)", "12–16"],
        ["Residential (premium)", "5,000–6,500", "2-kanal (9,000+ sqft)", "18–24"],
        ["Commercial office CAT B", "2,800–4,200", "5,000–10,000 sqft floor", "10–14"],
        ["Commercial office premium", "4,200–5,200", "HQ / executive floor", "14–18"],
        ["Retail / F&B", "5,000–9,000", "1,500–4,000 sqft", "8–12"],
        ["Turnkey (design+build)", "4,500–8,000", "Full scope", "14–22"],
        ["Renovation (cosmetic)", "1,500–2,500", "Any", "6–10"],
        ["Renovation (full gut)", "2,800–4,200", "Any", "14–20"],
        ["Custom furniture only", "1,800–3,800", "Per sqft of piece", "4–8 weeks"],
      ],
    },
    { type: "h2", text: "What's inside each number" },
    { type: "h3", text: "Residential PKR 3,500–6,500/sqft" },
    { type: "p", text: "Lower end assumes you're happy with mid-tier local tiles (PKR 250–350/sqft), local laminate/veneer joinery, standard sanitary ware (Porta / Dorset / Grohe imported lines are higher), false ceiling with standard LED downlights, and semi-modular kitchen in laminate." },
    { type: "p", text: "Upper end is premium veneer or lacquer joinery, Italian porcelain or imported marble, Grohe/Dornbracht fittings, imported kitchens (we typically work with local fabricators copying Italian details at 40% of the landed cost — indistinguishable in the finished room), smart home pre-wire, and proper acoustic treatment where needed." },
    { type: "h3", text: "Commercial office PKR 2,800–5,200/sqft" },
    { type: "p", text: "The huge variance here is about density and meeting-room ratio. Call-centre floors at 1:4 density with open plan and one meeting room for 20 people come in at PKR 2,800–3,200/sqft. Law firms and private-equity offices with 50% glazed partition ratio and executive offices land at 4,500–5,200/sqft." },
    { type: "h3", text: "Retail and F&B PKR 5,000–9,000/sqft" },
    { type: "p", text: "Retail is expensive because every surface is customer-facing, lighting matters more, and there is often commercial kitchen, HVAC capacity upgrades, fire-system upgrades, and façade/storefront work. The upper end is restaurants with commercial kitchens, imported finishes, and custom designer lighting." },
    { type: "h2", text: "Where the other quotes you get will be wrong" },
    { type: "ul", items: [
      "**They don't include MEP upgrades.** A 20-year-old DHA house will need rewiring and a new distribution board. That's PKR 350–550/sqft that shows up in variation orders in week six.",
      "**They quote 'laminate' but price the cheapest board.** There's a 4x price difference between the cheapest Chinese laminate and a Formica/Abet Laminati grade. Ask for the brand in writing.",
      "**They don't include false ceilings.** Many quotes say 'electrical' but not 'ceiling' — and you can't have the electrical without it.",
      "**Joinery quantities are estimated, not drawn.** Until someone draws every wardrobe and kitchen in 3D, the joinery number is a guess. We've seen a client's quote double when the joinery was finally measured.",
      "**GST.** If the contractor is registered, add 18% on top. If they're not, they can't supply to commercial clients and their material purchases don't carry input credit.",
    ]},
    { type: "h2", text: "The only number that actually matters" },
    { type: "p", text: "Per-sqft numbers are useful for sanity-checking but the number that actually matters is the **fixed, itemised quote** produced after drawings are signed off. In 11 years, 90% of budget blow-outs we've seen were because clients signed up to a per-sqft range and didn't demand a BoQ." },
    { type: "pullout", title: "Woodex rule of thumb", text: "If a quote is more than 15% cheaper than the midpoint of our published range, something is missing. Either the contractor plans to make it up on variations, plans to use cheaper materials than specified, or plans to not pay their labour (in which case you'll be redoing the job in 18 months)." },
  ],

  "12-week-cafe-fitout-timeline": [
    { type: "p", text: "We've been the contractor on 14 café and restaurant fit-outs in Lahore since 2019. This is the schedule we actually work to — not the marketing version. A 1,400–2,000 sqft café, shell condition (not previously a restaurant), takes **12 weeks on site** plus 2-3 weeks for design and approvals." },
    { type: "h2", text: "The week-by-week breakdown" },
    { type: "h3", text: "Pre-construction (weeks 0-2, off-site)" },
    { type: "ul", items: [
      "Landlord approval drawings submitted and consent received. This is critical — Packages, Emporium, and most DHA commercial areas take 10-14 days just to review drawings.",
      "Final 3D walkthrough signed off, BoQ locked, contract signed.",
      "Long-lead items ordered: commercial kitchen equipment (imported ovens/espresso machines can take 6-8 weeks), HVAC plant, feature lighting, imported tiles/marble.",
      "CDA/BDP permits filed (outdoor signage, seating on terrace if applicable).",
    ]},
    { type: "h3", text: "Weeks 1-2 on site: demolition and MEP rough-in" },
    { type: "p", text: "Demolition happens in the first 4 days. If the unit was previously a restaurant you save a week — if it was a retail shop, budget for coring through the slab for drainage (commercial kitchen waste is 110mm, bigger than anything retail uses)." },
    { type: "p", text: "By the end of week 2, all MEP rough-in is in place and pressure-tested: gas, water, drainage, electrical trunking, HVAC ductwork routes, fire alarm/suppression. This is the point at which we do a joint walkthrough with the client's kitchen supplier." },
    { type: "h3", text: "Weeks 3-5: civil works" },
    { type: "p", text: "Flooring, wall build-up, plaster, waterproofing in kitchen and washrooms. Waterproofing is where 90% of post-opening nightmares happen — we do two coats of polyurea membrane and a 48-hour flood test before any tile goes down." },
    { type: "h3", text: "Weeks 6-8: joinery and ceiling" },
    { type: "p", text: "This is where most sites save time — we build all fixed joinery (counter, banquettes, back-bar, display) off-site in our Sundar workshop during weeks 3-5 and install in days, not weeks. Ceiling goes in at week 7, first fix electrical at week 8." },
    { type: "p", text: "This is also where we see other contractors lose 3 weeks. If joinery is built on site by one carpenter, a 20 ft bar can take three weeks. We build it in parallel in our workshop with three joiners." },
    { type: "h3", text: "Weeks 9-10: finishes and equipment" },
    { type: "p", text: "Paint/veneer finishes, lighting install, tiling grouted, sanitary ware fitted. Commercial kitchen equipment lands week 9, gets connected week 10. HVAC commissioned. Fire system tested." },
    { type: "h3", text: "Week 11: snagging and soft-open" },
    { type: "p", text: "Joint snag list with the client on Monday. We resolve all items by Thursday. Friday is for staff training — kitchen gets fired up for the first time, POS, AV, music system all commissioned." },
    { type: "h3", text: "Week 12: handover" },
    { type: "p", text: "Final deep clean, professional photographs, key handover. A Woodex PM is on site for opening lunch service for the first day." },
    { type: "h2", text: "The three delays we plan for" },
    { type: "ol", items: [
      "**Landlord approval delays** are the single biggest reason for late openings. We submit drawings on day 2 of the contract, not day 14.",
      "**Imported kitchen equipment.** If you're specifying a La Marzocco or a Rational, order it the day you sign the lease — not after the contractor starts.",
      "**Gas connection.** Sui Gas can take 6-10 weeks for a new commercial connection. Start that on day one.",
    ]},
    { type: "quote", text: "A café opening date isn't a target. It's a cheque. Every day the doors are closed you're paying rent, paying your head chef, and losing the marketing moment of your launch.", cite: "Hamza Saeed, Senior PM Retail & F&B" },
  ],

  "why-we-publish-prices": [
    { type: "p", text: "In early 2024 I had a call with a potential client who had been shopping around for six weeks. She told me she'd had five designers visit her DHA home, and not one of them had given her a number. Every meeting ended with 'we'll come back to you with a proposal.' None of them did." },
    { type: "p", text: "This is standard practice in our industry and it's terrible for everyone. Designers hide pricing because they're scared of being compared, or they want to get to a 'trust' point before quoting, or they're going to quote high and see if you bite. The client loses six weeks and ends up picking whoever called them back." },
    { type: "h2", text: "What happened when we published numbers" },
    { type: "p", text: "We published per-sqft ranges on the Services page in March 2024, and a published price list for the 3D Studio in May. Here's what changed:" },
    { type: "ul", items: [
      "**Pre-sales call time dropped 60%.** Calls went from 25 minutes of 'how much roughly?' to 10 minutes of 'we're at X sqft, our budget is Y, can you do it by Z date.'",
      "**Lead quality went up.** People who can't afford PKR 5,000/sqft don't call. That saves both of us 20 minutes.",
      "**Lead-to-close rate went up.** Counter-intuitively, publishing a number made people trust us more. Our conversion from enquiry to site visit went from 28% to 41% in the quarter after publishing.",
      "**We lost three potential clients.** All three told us we were too expensive. Two came back six months later after their cheaper contractor went 40% over budget. One didn't, which is fine — they weren't our client.",
    ]},
    { type: "h2", text: "Why won't everyone do this?" },
    { type: "p", text: "There are three reasons, and none of them are flattering: either the studio doesn't actually know what their projects cost (no cost-tracking), they want to size you up and quote what they think you'll pay, or their business model is a low-ball number followed by variation orders. None of those produce a good outcome for the client." },
    { type: "quote", text: "If a designer won't tell you a rough number on the first call, that is information. Believe them." },
    { type: "p", text: "Our published ranges are honest ranges. About 80% of signed projects land in the middle 50% of the range, 10% come in under, and 10% come in over (usually because the client chose premium finishes after sign-off, in which case the change is documented and approved in writing before we do the work)." },
  ],

  "marble-vs-vietnam-marble": [
    { type: "p", text: "We get asked this on every residential project. The answer isn't 'marble is better' or 'porcelain is better' — each has a job, and the wrong choice in the wrong room will cost you money or look terrible after two years." },
    { type: "h2", text: "The three options, side by side" },
    { type: "table",
      headers: ["", "Pakistani marble", "Vietnamese marble", "Porcelain"],
      rows: [
        ["Cost (laid)", "PKR 280–650/sqft", "PKR 450–900/sqft", "PKR 350–1,200/sqft"],
        ["Stain resistance", "Low", "Medium", "Very high"],
        ["Maintenance", "Seal every 12-18 months", "Seal every 2-3 years", "None"],
        ["Feel underfoot", "Warmest", "Warm", "Cold, hollow"],
        ["Available sizes", "Up to 4'×8' (slab)", "Up to 6'×10' (slab)", "Up to 4'×8' (tile)"],
        ["Consistency", "High variation", "Moderate", "Near-perfect"],
        ["Repair if chipped", "Can be polished out", "Can be polished out", "Replace the tile"],
      ],
    },
    { type: "h2", text: "Pakistani marble (Verona, Ziarat, Badal, China White)" },
    { type: "p", text: "Beautiful, warm, and it ages with the house. The Verona cream and Ziarat white that you see in older DHA homes have a character nothing else matches. But Pakistani marble is porous. A dropped cup of chai will leave a ring. Red wine is a disaster. It needs sealing every 12-18 months or it will stain permanently." },
    { type: "p", text: "**Where we use it:** accent walls, stair treads in low-traffic homes, formal drawing rooms, powder-room floors. We do not use it in kitchens. We almost never use it in bathrooms with showers." },
    { type: "h2", text: "Vietnamese marble" },
    { type: "p", text: "Denser, harder, less porous than Pakistani marble, and available in larger slabs with less veining variation. This is what you want if you like marble but hate the maintenance. Carrara, Calacatta, and Statuario-look Vietnamese marbles are common in Lahore now." },
    { type: "p", text: "**The catch:** half the 'Vietnamese marble' in Lahore showrooms is Chinese marble that chips at the edges and fades in UV. Buy from a supplier who will let you see the slab yard, not just a showroom sample. Expect to pay at least PKR 600/sqft laid for the real thing; anything under PKR 500 is suspect." },
    { type: "p", text: "**Where we use it:** living areas, dining rooms, main lobbies, master bedrooms. We still don't use it in open kitchens if the client cooks desi food regularly." },
    { type: "h2", text: "Porcelain (large-format)" },
    { type: "p", text: "Porcelain tile is fired ceramic. It doesn't stain, doesn't need sealing, doesn't scratch, and modern 1200×2400 and 1600×3200 formats convincingly imitate marble and concrete. It will look the same in 15 years." },
    { type: "p", text: "The downsides: it feels colder underfoot in winter, sounds hollow when you walk on it (especially with heels), and if you drop a heavy cast-iron pan on it the tile chips and you can't polish it out — you replace the tile, which means keeping 2-3 spares in storage." },
    { type: "p", text: "**Where we use it:** kitchens, bathrooms, entrance foyers with heavy foot traffic, commercial floors, and any home with children under 8 or dogs." },
    { type: "h2", text: "Our default specification" },
    { type: "ul", items: [
      "**Kitchen:** porcelain, full-height splashback in the same material.",
      "**Living/dining:** Vietnamese marble (Carrara or cream), 24×24 or 32×32 laid in a straight grid.",
      "**Bathrooms:** porcelain floor, porcelain walls (wet areas), marble feature wall if the budget allows.",
      "**Drawing/formal room:** Pakistani marble if the client prioritises character and will maintain it; Vietnamese marble otherwise.",
      "**Stairs:** Vietnamese or Pakistani marble treads with a non-slip groove routed in.",
    ]},
  ],

  "hbl-model-town-case-study": [
    { type: "p", text: "HBL Model Town was a 6,400 sqft retail branch refresh on a 62-day programme — the client's standard branch-refit window. There were no extensions. There was no 'we'll open soft and finish the snag list.' Branch operations had to be fully live by day 63." },
    { type: "h2", text: "The scope" },
    { type: "ul", items: [
      "Full strip-out of existing finishes, teller line, and back-office joinery.",
      "New teller line with cash-counter ballistic protection.",
      "New digital signage, customer waiting area, two ATM lobbies refurbished.",
      "MEP upgrade: new distribution, LED lighting throughout, HVAC balancing.",
      "New reception, manager's office, two meeting rooms.",
      "Brand application per HBL's latest brand guidelines.",
    ]},
    { type: "h2", text: "The plan" },
    { type: "p", text: "The critical insight was that civil works have a 11-day curing period for concrete and floor screed. During those 11 days, nothing can happen on the floor — but joinery can be built off-site. We pre-built all joinery (teller line, reception, back-office storage, ATM surrounds) in our Sundar workshop during weeks 2-3 so that when the floor cured, the joinery arrived on a truck and was installed in 6 days." },
    { type: "p", text: "That one decision — off-site joinery during curing — is what made 62 days possible. On a linear programme this adds 14 days on the critical path." },
    { type: "h2", text: "The two things that nearly slipped" },
    { type: "p", text: "**1. Ballistic steel delivery.** The cash-counter steel panel was shipping from Islamabad and was 4 days late on the truck. We rearranged the sequence so all other teller-line works completed first and the panel was installed on a Saturday overnight. No impact on the programme." },
    { type: "p", text: "**2. Brand signage vendor.** The illuminated HBL logo was supplied by the bank's nominated vendor who missed their delivery date by 3 days. We installed the backing plate on schedule, mounted the logo the day it arrived, and completed the electrical connection in the same evening." },
    { type: "h2", text: "Handover" },
    { type: "p", text: "We walked the snag list with the HBL facilities team on day 60. There were 11 items: two paint touch-ups, three silicone lines that needed redoing, one door stopper, two light diffusers, three grout touch-ups. All were closed by day 62." },
    { type: "p", text: "The branch opened for business at 9am on day 63. Budget was PKR 2.14 crore; final PKR 2.11 crore — PKR 3.2 lakh under, because we procured lighting at a better rate than budgeted and passed the saving on." },
    { type: "pullout", title: "The number that matters most", text: "0 punch-list items above 150mm from finished floor at joint handover inspection. That's our target on every commercial project." },
  ],

  "9-mistakes-first-time-clients": [
    { type: "p", text: "We've been doing this 11 years. Here are the nine mistakes we see first-time clients make, in order of how much money they cost." },
    { type: "h3", text: "1. Hiring on 3D renders alone" },
    { type: "p", text: "A beautiful render tells you nothing about whether the contractor can build it. Ask to visit a finished project. Ask for the contractor's last three clients' phone numbers. Call them." },
    { type: "h3", text: "2. Buying property without checking MEP risers and structural constraints" },
    { type: "p", text: "Commercial clients routinely sign leases on floors where the toilet stack is in the wrong place, the HVAC can't be upgraded for their density, or the slab can't support a server room. A PKR 20,000 due-diligence visit before you sign saves PKR 20-40 lakh later." },
    { type: "h3", text: "3. Changing tile layout after it's laid" },
    { type: "p", text: "It sounds small but it means demolition, re-screed, re-waterproofing (if wet area), new material, re-tiling. This single change is PKR 2-5 lakh on a bathroom and two weeks on the programme." },
    { type: "h3", text: "4. Not budgeting a contingency" },
    { type: "p", text: "On renovation projects 10% is the minimum. On new-build 5%. Every old building hides something. Clients who budget zero contingency are the ones who stall at 80% when something unexpected comes up." },
    { type: "h3", text: "5. Paying 50% upfront" },
    { type: "p", text: "Our payment schedule is 6 milestones. Mobilisation is 15%. Nobody ever needs 50% to start. Anyone asking for it is either undercapitalised (risk of them disappearing mid-project) or planning to use your money to finish someone else's job." },
    { type: "h3", text: "6. Skipping the survey drawing" },
    { type: "p", text: "If your contractor doesn't laser-measure the space and produce a dimensioned drawing before quoting, their quote is a guess. We have seen bathrooms 'measured by eye' come out 8 inches too small for the ordered bathtub." },
    { type: "h3", text: "7. Specifying imported fittings without a local service agent" },
    { type: "p", text: "A German kitchen faucet that breaks in year two with no local agent means a paperweight. Specify brands with local representation, or keep a spare cartridge." },
    { type: "h3", text: "8. Approving changes by text message" },
    { type: "p", text: "Every change should be a written change order: scope, cost, impact on date. 'Can we move that wall a foot?' on WhatsApp turns into a PKR 2 lakh invoice at the end." },
    { type: "h3", text: "9. Scheduling handover against a family wedding date" },
    { type: "p", text: "If you absolutely must be in by a family event, work backwards from that date, add three weeks of buffer, and start earlier. The client who tells us 'we need to be in by Eid' in the middle of Ramadan has already lost." },
  ],

  "friday-report-explained": [
    { type: "p", text: "Before 2019 we didn't send structured weekly updates. We updated clients on WhatsApp when they asked. Sometimes that was every day. Sometimes a week went by. On a DHA Phase 6 project that went three weeks late in 2019 the client told me, at the end: 'I'm not angry that you were late. I'm angry that I didn't know until the Friday before you were supposed to hand over.'" },
    { type: "p", text: "That comment changed how we run projects. The Friday Report was the result." },
    { type: "h2", text: "What's in it" },
    { type: "p", text: "One page, PDF, sent every Friday at 4pm from the project lead's email address — not a marketing account. Four sections:" },
    { type: "ol", items: [
      "**Shipped this week** — what was completed, listed as bullets, with photos.",
      "**Shipping next week** — what's on the plan for the next seven days, including which trades will be on site.",
      "**Budget spent vs budgeted** — percentage against each major package (civil, MEP, joinery, finishes).",
      "**Risks and decisions needed** — anything that might affect the date or the budget, flagged red/amber/green with an owner and a deadline. If a decision is needed from the client, we state the deadline in writing.",
    ]},
    { type: "p", text: "Plus 6-15 site photos. Wide shots that show the real state of the project, not curated beauty shots." },
    { type: "h2", text: "What changed" },
    { type: "p", text: "On-time delivery went from 78% to 98% over the next 18 months. Not because we started building faster — because the Friday Report forced us to surface problems on Friday when we could still fix them, not on handover day when we couldn't. Clients stopped calling at 11pm. Disputes at the end of projects dropped to almost zero because there were no surprises." },
    { type: "quote", text: "The Friday Report isn't a marketing document. It's the opposite of marketing — it's the document that tells you what's going wrong, early, when you can still do something about it." },
  ],

  "retail-fitout-footfall": [
    { type: "p", text: "In late 2024 we designed and built a 920 sqft multi-brand fashion unit in Packages Mall. The client had been operating from the same unit for three years with their original fit-out and felt footfall had plateaued. We weren't allowed to change the merchandise or pricing. We changed only the space." },
    { type: "h2", text: "What we changed" },
    { type: "h3", text: "The threshold moved 1.2m into the mall corridor" },
    { type: "p", text: "The previous shop had a flush entrance — glass line aligned with the corridor wall. In a mall corridor, shoppers walk at about 1.2 m/s and make binary decisions at each storefront. A flush entrance means the decision to enter happens as you're already walking past. Moving the threshold 1.2m in created a 'decompression zone' where the shopper is already inside the shop's atmosphere before they decide to engage." },
    { type: "h3", text: "A lit central table instead of wall racks" },
    { type: "p", text: "Wall racks are designed for stock density, not for dwell time. We replaced the front third of the shop with a travertine-topped central table lit by a single warm pendant, with folded and styled pieces. Wall racks moved to the back 60%." },
    { type: "h3", text: "Cashwrap at 2/3 depth, not at the back" },
    { type: "p", text: "Checkout at the back forces a 'U-shaped' path and creates a dead zone in the middle third. Moving the cashwrap to 2/3 depth let browsers see the whole shop from the entrance and meant staff at the till could greet people as they walked in." },
    { type: "h2", text: "The numbers, eight weeks post-opening" },
    { type: "ul", items: [
      "Footfall: up 38% vs the same 8 weeks the previous year (mall overall was up 6%, so 32pts above baseline).",
      "Average dwell time: 1:40 → 4:12.",
      "Conversion: 4.1% → 6.8%.",
      "Average transaction value: unchanged. People weren't spending more; more of the people who walked in bought.",
    ]},
    { type: "p", text: "Build cost was PKR 72 lakh. At the new conversion rate and average transaction, the client estimates the fit-out paid for itself in 14 weeks." },
  ],

  "3d-renders-match-build": [
    { type: "p", text: "The most common complaint we hear from clients about previous designers is 'the render looked nothing like the finished space.' There's a reason for that: most renders are sales tools. They use manufacturer marketing photos for materials, generic HDRI lighting (shot in California, not Lahore), and furniture from 3D libraries that isn't actually available in Pakistan." },
    { type: "p", text: "Our 3D team follows three rules that get us to about 95% match." },
    { type: "h3", text: "1. We build our own material library" },
    { type: "p", text: "Mariam, our head of 3D, doesn't download materials. We go to the marble yard, to the timber merchant, to the tile supplier, take 30-40 photos of each material in flat afternoon light, and build calibrated PBR materials from those photos. When she renders 'oak veneer matte' it's the oak veneer we actually buy in Anarkali, not a generic 3D asset." },
    { type: "h3", text: "2. We light with Lahore light" },
    { type: "p", text: "Lahore is at 31.5°N latitude. In summer at 5pm the sun is at a specific angle and colour temperature (about 3500K through our summer dust). Generic HDRI environments are shot in European or Californian light and look wrong. We have built our own HDRIs from site visits on Lahore projects." },
    { type: "h3", text: "3. Renders are re-done against the construction drawings" },
    { type: "p", text: "Concept renders are marketing. The 'final' render that goes into the contract is re-rendered against the signed-off construction set — the same drawings the carpenter has. If the joinery detail changed in the drawing set, it changes in the render too." },
    { type: "h2", text: "The 5% gap" },
    { type: "p", text: "The last 5% is about small things: how the fabric on the sofa creases, a slight colour shift from a tile batch, a plant that's bigger or smaller than the one in the model. That's normal. If you can't tell the difference in a side-by-side photo, we consider it a match." },
    { type: "quote", text: "If a render looks too good to be true on a Lahore budget, it is. Ask the studio to show you the render next to a finished photo, unposed, of the same room." },
  ],
};
