/**
 * Sanity project bootstrap script.
 *
 * Run after you've created the Sanity project and have a Project ID + write token:
 *   npx tsx src/scripts/bootstrap-sanity.ts
 * or:
 *   SANITY_PROJECT_ID=xxx SANITY_AUTH_TOKEN=xxx npx tsx src/scripts/bootstrap-sanity.ts
 *
 * What it does:
 *   1. Adds CORS origins (localhost + vercel + production domain)
 *   2. Writes a .env.local with the credentials (for local dev)
 *   3. Prints the exact Vercel env var commands
 * Does NOT deploy by itself (no Vercel token in sandbox).
 */
import { createClient } from "@sanity/client";
import { writeFileSync } from "fs";
import { join } from "path";

const projectId = process.env.SANITY_PROJECT_ID!;
const token = process.env.SANITY_AUTH_TOKEN!;
const dataset = process.env.SANITY_DATASET ?? "production";
const productionUrl = process.env.PRODUCTION_URL ?? "https://agent-woodex.vercel.app";

if (!projectId || !token) {
  console.error("Set SANITY_PROJECT_ID and SANITY_AUTH_TOKEN env vars first.");
  process.exit(1);
}

const client = createClient({
  projectId,
  dataset,
  token,
  apiVersion: "2025-01-15",
  useCdn: false,
});

async function main() {
  console.log(`\nProject ID: ${projectId} / dataset: ${dataset}\n`);

  // 1. Test credentials
  try {
    const res = await client.request({ url: "/projects/" + projectId });
    console.log(`✓ Authenticated as project "${res.displayName || res.name || projectId}"`);
  } catch (e: any) {
    console.error("✗ Auth failed:", e.message);
    process.exit(1);
  }

  // 2. Print CORS instructions (can't set CORS via client without /projects API)
  console.log(`\n→ Add these CORS origins at https://sanity.io/manage/project/${projectId}/api#cors-origins`);
  console.log(`    http://localhost:3003            (allow credentials ✓)`);
  console.log(`    http://localhost:3000            (allow credentials ✓)`);
  console.log(`    ${productionUrl}        (allow credentials ✓)`);

  // 3. Write .env.local for local dev
  const envLocal =
`# Auto-generated by bootstrap-sanity.ts — added to .gitignore
NEXT_PUBLIC_SANITY_ENABLED=true
NEXT_PUBLIC_SANITY_PROJECT_ID=${projectId}
NEXT_PUBLIC_SANITY_DATASET=${dataset}
SANITY_API_READ_TOKEN=${token}
SANITY_REVALIDATE_SECRET=woodex-revalidate-secret-change-in-prod
`;
  writeFileSync(join(process.cwd(), ".env.local"), envLocal);
  console.log(`\n✓ Wrote .env.local`);

  // 4. Print Vercel env commands for the user
  console.log(`\n→ Run these Vercel CLI commands to set env vars in production:`);
  console.log(`    npx vercel env add NEXT_PUBLIC_SANITY_ENABLED production  # enter: true`);
  console.log(`    npx vercel env add NEXT_PUBLIC_SANITY_PROJECT_ID production  # enter: ${projectId}`);
  console.log(`    npx vercel env add NEXT_PUBLIC_SANITY_DATASET production  # enter: ${dataset}`);
  console.log(`    npx vercel env add SANITY_API_READ_TOKEN production  # paste the sk... token`);
  console.log(`    npx vercel env add SANITY_REVALIDATE_SECRET production  # pick a strong secret, same as PREVIEW_SECRET`);
  console.log(`    npx vercel --prod`);
  console.log(`\n→ After redeploy, seed pages:`);
  console.log(`    curl -X POST ${productionUrl}/api/seed-builder \\`);
  console.log(`      -H "Authorization: Bearer <PREVIEW_SECRET>" \\`);
  console.log(`      -H "Content-Type: application/json"`);
  console.log(``);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
